Repository CodethinkLabs/bloodlight-firmware, pull requests merged in 2020-10, with the labels that each got.

#67 firmware: Enable oversample in ADC enable instead of config
  src/acq/adc.c
Labels: firmware

#69 Tlsa/bloodview improve
  bloodview/README.md
  bloodview/sdl-tk/include/sdl-tk/widget.h
  bloodview/sdl-tk/include/sdl-tk/widget/custom.h
  bloodview/sdl-tk/src/util.h
  bloodview/sdl-tk/src/widget/action.c
  bloodview/sdl-tk/src/widget/input.c
  bloodview/sdl-tk/src/widget/menu.c
  bloodview/sdl-tk/src/widget/select.c
  bloodview/sdl-tk/src/widget/toggle.c
  bloodview/sdl-tk/src/widget/widget.c
  bloodview/src/device.c
  bloodview/src/graph.c
  bloodview/src/graph.h
  bloodview/src/main-menu.c
  bloodview/src/main-menu.h
  bloodview/src/sdl.c
  tools/msg.c
Labels: control, data science, enhancement, front end, host

#70 Tlsa/bloodview scale
  bloodview/src/graph.c
Labels: cleanup, enhancement, front end, host

#73 Tlsa/bloodview fast scale
  bloodview/src/graph.c
Labels: enhancement, front end, host

#74 Tlsa/derivatives
  bloodview/Makefile
  bloodview/resources/main-menu.yaml
  bloodview/src/data.c
  bloodview/src/derivative.c
  bloodview/src/derivative.h
  bloodview/src/main-menu.c
  bloodview/src/main-menu.h
Labels: data science, enhancement, front end, host

#75 bloodview: graphs: Show current rendering scale factor.
  bloodview/src/graph.c
Labels: data science, enhancement, front end, host

#76 Benbrewer/callback optimization
  src/acq/adc.c
  src/acq/adc.h
  src/acq/channel.c
  src/acq/channel.h
  src/acq/dac.c
  src/acq/dac.h
  src/acq/dma.c
  src/acq/dma.h
  src/acq/opamp.c
  src/acq/opamp.h
  src/acq/rcc.h
  src/acq/source.c
  src/acq/source.h
  src/acq/timer.c
  src/acq/timer.h
Labels: firmware, optimisation
