Repository CodethinkLabs/bloodlight-firmware, pull requests merged in 2020-09, with the labels that each got.

#48 Bloodview: Calibration support for revision 1
  bloodview/Makefile
  bloodview/src/data-avg.c
  bloodview/src/data-cal.c
  bloodview/src/data-cal.h
  bloodview/src/data.c
  bloodview/src/device.c
  bloodview/src/locked.h
  bloodview/src/main-menu.c
  bloodview/src/main-menu.h
  bloodview/src/sdl.c
Labels: control, data science, front end, host, revision 1, testing

#55 Split concepts of sources and channels and expose rev2 source attributes
  Makefile
  bloodview/src/device.c
  bloodview/src/main-menu.c
  bloodview/src/main-menu.h
  run.sh
  src/acq.c
  src/acq.h
  src/acq/adc.c
  src/acq/adc.h
  src/acq/channel.c
  src/acq/channel.h
  src/acq/dac.c
  src/acq/opamp.c
  src/acq/source.c
  src/acq/source.h
  src/acq/timer.c
  src/error.h
  src/mq.c
  src/mq.h
  src/msg.c
  src/msg.h
  tools/bl.c
  tools/calibrate.c
  tools/msg.c
Labels: cleanup, comms, control, data science, enhancement, firmware, front end, host, revision 2

#64 Fix minor issue in bl tool usage
  tools/bl.c
Labels: bug

#63 Add libfftw3 dependency to README
  README.md
Labels: documentation
